# MC Position Control Parameters for logging
uint64 timestamp      # in microseconds since system start
float32 MPC_X_P
float32 MPC_X_VEL_P
float32 MPC_X_VEL_I
float32 MPC_X_VEL_D
float32 MPC_X_VEL_MAX
float32 MPC_X_FF
float32 MPC_Y_P
float32 MPC_Y_VEL_P
float32 MPC_Y_VEL_I
float32 MPC_Y_VEL_D
float32 MPC_Y_VEL_MAX
float32 MPC_Y_FF
float32 MPC_Z_P
float32 MPC_Z_VEL_P
float32 MPC_Z_VEL_I
float32 MPC_Z_VEL_D
float32 MPC_Z_VEL_MAX
float32 MPC_Z_FF